### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by riguy724** [winstonjs/winston-redis#23]
Is there any support for error handling when a redis instance is not available?  Currently the transport will just hang until it crashes.  We want to use it as a transport in cases where the redis broker for messages is available and accepting messages, but not have the app crash if its unavailable or goes away while things are running.  I can't really find a good solution of allowing this.

**Comment by yads** [comment]
You can subscribe to the `'error'` event on the transport. Would that be what you are looking for?

**Comment by bmcswee** [comment]
@yads answer worked for me. Subscribing to the error event on the transport prevents the error from bubbling up as an uncaught error that causes Node to exit.

`global.winstontransport = new winston.transports.Redis(options);
global.winstontransport.on('error', function(err) {
  console.error("winston redis transport error", err);
});`
