### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by yads** [winstonjs/winston-redis#24]
@indexzero @chjj can you guys take a look at master and see about releasing this to npm? Any thoughts on versioning? It should be backwards compatible with v1.0, however, I've moved winston and redis into peerDependencies. So I'm not sure if that would be considered a breaking change.

**Comment by indexzero** [comment]
@yads I'm currently on vacation, but returning to work on Tuesday. Will take a look at the latest this week.

**Comment by aestock** [comment]
bump

**Comment by yads** [comment]
@indexzero if you need some help with getting these releases out, you can give me npm push access, as I already have github access.

**Comment by DABH** [comment]
Consolidating the "publish new version" issues but hopefully @indexzero can give @yads and/or @mgibeau npm push access for this repo soon so we can get the winston@3-compatible version out there.  (One can use master in the meantime if urgent.)  Thanks!
