### ISSUE TITLE
npm version is different then master

### ISSUE THREAD

**Issue by finalclass** [winstonjs/winston-redis#25]
For example this line is not published:
https://github.com/winstonjs/winston-redis/blob/master/lib/winston-redis.js#L104
Could you publish the current version to npm please?

**Comment by DABH** [comment]
Consolidating the "publish new version" issues but hopefully @indexzero can give @yads and/or @mgibeau npm push access for this repo soon so we can get the winston@3-compatible version out there.  (One can use master in the meantime if urgent.)  Thanks!
