### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by jtara1** [winstonjs/winston-redis#32]
I'm running the beta version of this module and an bit older version of node
winston-redis@3.0.0
node v7.10.1

in line 84 of lib/winston-redis.js 

https://github.com/winstonjs/winston-redis/blob/master/lib/winston-redis.js#L85

```
    const { level, message, ...winstonMeta } = info
    const meta = Object.assign({}, winstonMeta, this.metadata)
```

the `...` operator is usually used with unpacking the values of an array or skipping over values during the deconstruction of an array.

maybe there's a different use of this operator that I don't know about in a newer version of js?

what's the intended behavior of these two lines?

full stack trace:
```
/path/node_modules/winston-redis/lib/winston-redis.js:84
    const { level, message, ...winstonMeta } = info
                            ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/utils/logger.js:2:1)
```

**Comment by mgibeau** [comment]
Sorry, I've been meaning to document the new requirements for a while now. This is expected to work in Node 8.11.x.

What you're looking at is the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals), essentially, it's a fancy way of referencing all the "other" properties into a new object.

The intent is to merge Winston's "native" metadata with Winston-redis' (see #21). This was done for backward compatibility reasons but, I'm not sure how widespread it's used. I would actually be open to removing that portion as I find it confusing to support two different metadata models.

**Comment by mgibeau** [comment]
Updated the documentation with the new requirements
