### ISSUE TITLE
Meta data should be logged at the top level

### ISSUE THREAD

**Issue by mooski** [winstonjs/winston-redis#34]
Given this code:

    logger.log({
        level: 'info',
        message: 'My message',
        additional: 'More stuff'
    });

Other transports, such as File transport, log this JSON:

    {"level":"info","message":"My message","additional":"More stuff"}

Whereas winston-redis logs this JSON:

    {"level":"info","message":"My message","meta":{"additional":"More stuff"}}

Is it possible to add an option to log the meta data at the top level rather than as a child property?

**Comment by mgibeau** [comment]
Hi Mooski, sorry for the delay, saw your PR, I think it makes sense, would be happy to accept this option.
